# The re-connection (January - March) {- #reconnect}

## 2014-02. Letter to the deaths. - Self-deception {-#todeath201402}
Hello Tom (1991 - 2007)

Hello Monica (1989 - 2011)

I’m writing to you in a selfish way. Because I need you. I need to write to someone. I need to tell someone what I’m learning . I’m self- deceiving  myself, thinking that I’m not taking time out from you, because for you there is nothing left. You have plenty of time now that you’re not here. I’m deceiving myself because I need you. I need to write to you.

I think I’m giving you something, and even  dead, I’m taking away from you. I hope you are in peace, and I’m not bothering you with this letter.  I need people, I need the lies. Still. I just realise that I am not going to be able to study the Social Networks Master’s Degree next year, since I missed the deadline. It seems even  funny to know that I was already dead. I had been dead for a month and I didn’t know it. That I had one of the happiest weeks of my life and my future was dead. That I was living the present, happy. Filled with wellbeing . Helping the world. All of this thanks to my past, thanks to forgetting my past, to emptying my heart, filling my stomach, weakening my ambitions and strengthening my bones. I was happy, infinitely happy. Blooming, productive. In less than a week I went from consuming cannabis to considering seriously not killing  animals for my own benefit or consumption.

I abandoned my self,  my egoism. I have emptied myself, my morality is now  focused on the other.  I couldn’t steal if its other’s belongings, I couldn’t steal knowing that somebody needs  more than me. I couldn’t breathe if my oxygen would cause someone else’s death. I’ve given in, I’ve emptied myself. But I fill myself. I fill myself often.

Ambitions. I need this letter for working for the world, for them, for those alive. For every person that is still here. I needed to talk to those over there to realise that I have to work for this world. I must share this happiness and wellbeing that I have achieved. To spread and to give. Life is giving, therefore I’m begging to the Death. So that the Death gives to life what it takes from it.  

From a cemetery,I’m writing. From a cemetery, I learn. Because the living, with thedead, are still connected. That is why I want to study Social Networks becausekeeping my happiness is selfish because watching suffering calmly is selfish,being willing to change is ambition, but enjoying other’s suffering is egotistic.

And I’m alone, and I’m not alone. Because people exist. Because I cannot change anybody. The change is within each one, and outside, through writing. Talking to the dead and taking from the Death what it takes from us every day. We want It to give our life back. But prayers are selfish, writing is sharing. I’m writing for myself and on behalf of others. Because my letters have a receiver, even if they’re dead. Because it remains written, and any alive person will read it. Because I empty myself giving, and I fill myself back by emptying other people. Because I search for calm, and I give calm. I don’t hold it. 

Icreate emptiness in my body, so I can host others within me. 

And I don’t ask for anything in return. I don’t ask for anything they aren’t willing to give. I have air, water, food, and people. I have an empty glass to be filled.


## 2014-02-11 From P. {-#frompaloma20140211}

Hello Carlos, how's it going? 

The missing one... I guess you've been traveling, haven't you? Morocco, isn’t it?? Ui, ui, that healthy envy. Surely it has been an experience, tell me things. 

I'm going to Bristol this week to see some friends and see if I can disconnect a little. What's that about you losing your phone? I hope that you solve it soon. You are such a mess!!

Well, how were the exams? I suppose fucking nicely or at least well. You're probably already handling yourself speaking English very very well, Manuel. Hahahahahaha. And what plans do you have for this quarter?? 

I've finished the exams and I did nice although I haven't yet been given the psychosocial mark. They're so slow. And nothing… All subjects pass and that. Although I am aiming for more. Now starting the next quarter and I think that the party is gonna be over… Many assignments and many classes to which I have to go necessarily. In fact, right now, I am in "*Psychology of personality*", and it seems to me that participation and ass-kissing count more than anything else. Hahaha. I also wanted to ask you for an opinion on how to work on the subjects and all that, and which are themost interesting and so on. But well, you will tell me if you remember. I have: personality, critical thinking, health, linguistic and cognitive development, and psychological evaluation. When you can and feel like it, you tell me what you want. I relied too much on your advice that has always been good for me.

Regarding my life, not so much novelty: living in Salamanca and disconnected a little bit from my life from before, honestly... I want to do new thingsssss!!!! So that's what I tell youuu. I hope you enjoy the quarter and we talk soon, ok? Be happy!!

A huge kiss, freak!


## 2014-02-11 To P. {-#topaloma20140211}

Hello P.,
 
I'm all very well. I arrived yesterday from Morocco. A fantastic experience. I'm writing a chronicle of the trip, so when I finish it I will send it to you so that you give me your opinion before posting it on the blog. 
 
When you travel, open your eyes, talk to people, ask them the most basic and absurd thing you can think of. The world is full of nuances to taste. Leave your phone in airplane mode during the day. Enjoy the moment. Others can wait for a while for them to know how you're doing. Take pictures of everything that deserves a photo. Good pictures, you know how to take them. But leave the best moments for your memory. Don’t photograph those.
 
The stars of the Sahara sky cannot be photographed with the smartphone. The sunset on the mountainous horizon while I was meditating/praying on a dune, can't be photographed either. I got goosebumps every time I think about it.
 
If you really want to disconnect, don't worry about others. Your time is yours. You can tell them you're going to be out there and when you get back, you'll let them know.
 
The cell phone has appeared. It's at Charleroi Airport. It's 20€ transport to go back and forth. So, I will see if I can find someone who can pick it up for me. It makes me think it showed up. I think a lot about how I have behaves in the past with the goods that didn't belong to me. I need time to think about that...
 
My grades are given to me on the 13th of February. Everything went pretty good. I'll tell you when I know numerically. English works in ups and downs, oscillating.
 
Plans for the quarter: too many. But at least I'm getting used to not using the computer/smartphone, writing by hand and sleeping less than six hours. We will see what are the results...
 
Don't use your smartphone/computer when you're in class. Look at the professor's face. They will have already explained to you how important feedback is at this point. Live in the moment. Technology is a tool, not a part of you. You don't go with a hammer to class and you start hitting the table. Even if you can. Every tool has its moment. Control the tool so the tool won't control you. Look with your eyes and think with your brain. Write with your hands.
 
About the subjects of this quarter.
 
Personality. I got a distinction with honors. It's true it's about "ass-kissing". Interest, curiosity, participation are prettier words, though. Palenzuela is a pretty active, nocturnal person, like me.  We got and get along pretty well. He's not the best teacher, he gets messy with the ideas quite often. But it makes you think twice as much, so you can build on your own what he means. Take it as a challenge, not as a threat.
 
Critical thinking. I did almost every assignment with an incredibly hard-working girl. She did most of them. Read the book and take it as a guide. It's all there. Silvia was my teacher. Very friendly, nice and accessible. We got along very well.
 
Health. G. also gets messy by himself. Sometimes he explains things in one practice group that he doesn't explain in another. Compare your notes with people from other groups and take lots of notes in the theoretical class. He knows a lot. If you're interested, ask questions. However, well, it's clinical psychology, and it wasn't my favorite subject.
 
Evaluation. If C. G. is your teacher, go to class and copy everything she says. Looks like a dictation. It's kind of ridiculous for a university class, but it's what he asks on the exam. Go to the practice class. If it Genaro is not your teacher, I have no idea.
 
Cognitive development. Read the articles before you go to class. Go to the library one afternoon, no phone or computer. Take a couple of hours to read it. You're going to make the most of the class and save time in May. The work is long and tiresome. Try to anticipate and get it done with time. It's pretty methodical, so you don't have to think too much, but you have to work a lot. It takes time.
 
Live the present, P.. Quit technology and meet people. You don't tell everyone everything you do. Write something for yourself. Handwrite. Do things one at a time. Focus on what you're doing and forget problems you can't fix right now. Note them up so you won't forget about them and you'll fix them in the future.  Learn and let yourself be influenced. Don't prejudge, as much as it is possible. You're smart enough to make your decisions on your own. But if you need help, ask for it. Always.
 
We're in touch, P..
 
I also attach to you the work I did in Personality. It's two pages. Pa. quite liked it, so you can trust it to be fine. But he'll remember, so don't copy it. I hope it will guide you. Don't get stuck with the writing question. Read it slowly, and if you don't understand something it's normal. You haven't studied it yet. I think the terms “personality process” and “personality in action” are reversed. That's what he corrected when I gave it to him. Personality in action is the operation of the personality in process and the personality state is the result of the personality process. Don't trust me too much, wait for May. When you read it again everything will make more sense and you can correct my work.
 
A kiss,
 
Carlos.


## 2014-02-17 To T. {-#totomas20140217}

Hello Tomas
 
Today I feel a little tired, I suppose it is because it is already night, my throat hurts and I am considering taking some caffeine or going to rest.
 
I am writing to you briefly to tell you about my “successful” completion of the first semester as an Erasmus. At least academically. All passed.
 
In general, I am in quite a good mood and I have taken this past week to organize my schedule and prioritize my projects. Re-adapting to student life after my trip to Morocco. (There is a chronicle of the journey in hand; hands paralyzed unfortunately ...)^[6 years of paralysis already.] Still, I think I want to do too much and often go overwhelmed. I plan to write down a motivating message about the difference between moments of inspiration and day-to-day work. Maybe it will work. I'm not sure how to carry out everything I want. I have a schedule with almost no breaks, it is somewhat unreal… In moments of euphoria I write down my ideas and fit them into non-existent hours throughout the week.

I would also like to write more (I have noted down to write at least once a day, either reflectively or communicatively, like right now). With the subject of writing many times it is the first impulse to start writing what I lack. If you have any advice on how to remedy that primordial spark, I would really appreciate it.
 
Anyway, let's stop egocentric banalities. I would like to know about you, your family and your projects.
 
I hope everything is going well.
 
An affectionate hug and thanks for your time.
 
Carlos

## 2014-02-20 To L. {-#tolucia20140220}

>it went off
>she is not here
>she is not now and she has not been
>she could be dead right now
>or have been
>
>you were talking with pixels
>with a screen
>it was a recording
>in its due time
> 
> time
 
  
Hi L.,
 
The phone just went off and I wanted to continue talking to you. For this reason, I am writing (by hand, obviously).
 
The first thing that came to mind was the verses you just read. That is why they are the first written thing, it is a reliable and chronological representation of the handwritten sheet of paper.
 
At the time the phone was turned off, I was close to feeling anxiety and concern that I could not continue talking to you. But now I'm doing it. I feel like I'm communicating with you. I feel better. I have simply had to overcome the first instinct of inactivity or search for technological contact with you. I have started writing.
 
Even if I am writing this letter at night, you may read it tomorrow, in a week, or in a month. When I want to send it to you, if I send it to you. You may reread it in years and each time it will be different for you. You will be able to read this letter if I die before you and it will appear that I am speaking to you. (This is how I just beat death. This letter is my song ... (Tweet in English. Food for thought, isn’t it?))
 
Poetic parenthesis.
 
>... And I will leave. And the birds will stay
>singing;
>and my garden will remain, with its green tree,
>and with its white well.
>
>Every afternoon the sky will be blue and placid;
>and they will play, as they are playing this afternoon,
>the bells of the bell tower.
>
>Those who loved me will die;
>and the town will become new every year;
>and in the corner, that of my flowery and whitewashed garden.
>my spirit will wander, nostalgic ...

>And I will go away; and I'll be alone, homeless, treeless
>green, without white well,
>without blue and placid sky ...
>And the birds will stay, singing.

>Wild poems (1910-1911). [Juan Ramón Jiménez]( https://en.wikipedia.org/wiki/Juan_Ram%C3%B3n_Jim%C3%A9nez). [@jimenez1970tercera]
 
 
This is what technology has demolished. Haste has wiped out patience. The wait, the tasting of the moment, the pleasure of the non-immediate ... The enjoyment of one's own personality, of internal communication. Ultimately, life itself.
 
I don't want to continue writing, so you start doing it. But this little letter/reflection is clear proof of the benefits of writing and the harmfulness of digitized communication. In a few lines and almost without arguments.
 
Now, I start reading. I'm much more relaxed than I was five minutes ago when the phone went off. Also, writing this seems much more real to me than sending you a WhatsApp : “* I'm fine*”. Although it will take days, hours or years to send it to you, or you to read it, for me it has been much more immediate than a WhatsApp.
 
Good night.
 
A huge hug.

P.S. You know I would like to hear from you. (General and extremely open question that you can answer with the degree of detail and specificity that you want). If you want to just write to me that you are fine, I will believe it and continue my life placidly. Taking advantage of my time knowing that L. is happy. Lying to me is lying to yourself.


## 2014-02-21 To S. {-#tos20140221}

2014-02-21

Sheila
 
Patience is a really beautiful virtue that gets corrupted by the abuses of technology. Sincerity is the delicious fruit of patience.
 
You asked me a few weeks ago how I was doing, and I replied that at that time I did not have time to respond adequately, that I would write to you in the future. That future is today. I consider that it is a good moment to tell you a little about how I am.
 
I couldn't answer you when you asked me because I didn't have enough time. Also, I was not comfortable answering you in a hurry and without the care and detail that you deserve, and I deserve. I hope it hasn’t arrived bad and that you understand it. I like to take care of communication. I am willing to sacrifice speed for quality. So, I hope your answer, if any, is not hasty. Make it honest, of high-quality. I don't care how long it takes you to write to me, it can be two days, or it can be two years. I'll be fine.
 
In these moments I am very happy. I am very comfortable with my life. I am flourishing, I am incredibly productive. As I never have been. I am learning a lot: I read, I write, I meet incredible people, who show me new horizons and expand my mind; I tear down walls of the past; I understand part of the numerous mistakes I made in the past. But I don't blame myself. Those mistakes are part of my life, of my learning, of being where I am today. I needed to make a mistake to get where I got to. Sometimes it was necessary to be wrong once, but other times it was necessary to be wrong again and again. Enough times until I learned. Many of my mistakes have revolved around you. It had to be this way to learn. If they happen again, it will be equally necessary. It will be proof that I have not yet learned what I have to learn, that I have to continue learning.

Now I am understanding countless things that were incomprehensible to me in the past. That, at times, I acted in a completely illogical, extremely passionate way. Many times, in a hurry and worried about the ephemerality of the moment.
 
Now I'm calm. Much calmer.

In these moments of inner calm, few external storms can stir my spirit.
 
S., I would like to hear from you. You are a person whom, I feel, I have not treated as you deserve. I can learn a lot from you, and I have a feeling that we could have an incredibly fruitful relationship for both of us. No matter the physical distance, as long as there is a spiritual, intellectual, and / or emotional union. The power of the non-physical knows no limits in time or space. (Imagine reading this letter and that I am dead. You could still answer it and be communicating with me.)
 
Out of respect; towards me, but much more important, out of respect for you; I hope you will give me a thought worthy of your ability. If you lie to me, you are lying to yourself. I wrote a couple of days ago to a friend, who told me to that she was "*fine*". Personally, I highly doubt it. So, if that is not true, there is nothing I can do as a friend to help her. But, much more damaging, for both of them, I will believe that there is nothing wrong in not helping her. Lying to me is lying to yourself.
 
 
I would like you to answer me, please. Slowly and sincerely. If you do not want to answer me, I perfectly respect your decision.
 
Carlos


